In [4]:
import numpy as np
import pandas as pd

In [9]:
raw_data = {
    "ID" : [1,2,3,4,5,5],
    "Name" : ["Lakhvir", "Manish", "Damini", "Parmeet","Cheema", "Cheema"],
    "Age" : [20, np.nan, 19, 45, 21, 21],
    "Gender" : ["M", "M", "F", np.nan, "M", "M"],
    "Salary" :[50000, 55000, 45000, 40000, 35000,35000],
    "City" :["Banga", "Apra", "Barnala", "Jalandhar", np.nan, np.nan]
    
}

df = pd.DataFrame(raw_data)
print(df)

   ID     Name   Age Gender  Salary       City
0   1  Lakhvir  20.0      M   50000      Banga
1   2   Manish   NaN      M   55000       Apra
2   3   Damini  19.0      F   45000    Barnala
3   4  Parmeet  45.0    NaN   40000  Jalandhar
4   5   Cheema  21.0      M   35000        NaN
5   5   Cheema  21.0      M   35000        NaN

### Understanding the data

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      object
 2   Age     5 non-null      float64
 3   Gender  5 non-null      object
 4   Salary  6 non-null      int64
 5   City    4 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 420.0+ bytes

In [12]:
df.head()

   ID     Name   Age Gender  Salary       City
0   1  Lakhvir  20.0      M   50000      Banga
1   2   Manish   NaN      M   55000       Apra
2   3   Damini  19.0      F   45000    Barnala
3   4  Parmeet  45.0    NaN   40000  Jalandhar
4   5   Cheema  21.0      M   35000        NaN

In [13]:
df.shape

(6, 6)

In [14]:
df.describe(include="all")

              ID    Name       Age Gender        Salary   City
count   6.000000       6   5.00000      5      6.000000      4
unique       NaN       5       NaN      2           NaN      4
top          NaN  Cheema       NaN      M           NaN  Banga
freq         NaN       2       NaN      4           NaN      1
mean    3.333333     NaN  25.20000    NaN  43333.333333    NaN
std     1.632993     NaN  11.09955    NaN   8164.965809    NaN
min     1.000000     NaN  19.00000    NaN  35000.000000    NaN
25%     2.250000     NaN  20.00000    NaN  36250.000000    NaN
50%     3.500000     NaN  21.00000    NaN  42500.000000    NaN
75%     4.750000     NaN  21.00000    NaN  48750.000000    NaN
max     5.000000     NaN  45.00000    NaN  55000.000000    NaN

In [15]:
df.isnull().sum()

ID        0
Name      0
Age       1
Gender    1
Salary    0
City      2
dtype: int64

## Removing duplicates

In [25]:
df.drop_duplicates()
df

   ID     Name   Age Gender  Salary       City
0   1  Lakhvir  20.0      M   50000      Banga
1   2   Manish  25.2      M   55000       Apra
2   3   Damini  19.0      F   45000    Barnala
3   4  Parmeet  45.0    NaN   40000  Jalandhar
4   5   Cheema  21.0      M   35000        NaN
5   5   Cheema  21.0      M   35000        NaN

## handling missing values

In [24]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

   ID     Name   Age Gender  Salary       City
0   1  Lakhvir  20.0      M   50000      Banga
1   2   Manish  25.2      M   55000       Apra
2   3   Damini  19.0      F   45000    Barnala
3   4  Parmeet  45.0    NaN   40000  Jalandhar
4   5   Cheema  21.0      M   35000        NaN
5   5   Cheema  21.0      M   35000        NaN